// @flow

export const AUTH_SUBMIT_REQUEST = "AUTH_SUBMIT_REQUEST";
export const AUTH_SUBMIT_SUCCESS = "AUTH_SUBMIT_SUCCESS";
export const AUTH_SUBMIT_FAILURE = "AUTH_SUBMIT_FAILURE";

export const GET_CHATLIST_REQUEST = "GET_CHATLIST_REQUEST";
export const GET_CHATLIST_SUCCESS = "GET_CHATLIST_SUCCESS";
export const GET_CHATLIST_FAILURE = "GET_CHATLIST_FAILURE";
